### ISSUE TITLE
MGN Rail sizes

### ISSUE THREAD

**Issue by Renidd** [Gutter-Guys/Gutter_Rat#23]
current required equipment states.
2x MGN9 rails for Y gantry (MGN12 will not fit inside the panels)
Should read
2x MGN9 (350mm) rails for Y gantry (MGN12 will not fit inside the panels)

and 
1x MGN12 rail for X gantry (EVA now only supports MGN12)
should read
1x MGN12 (350mm) rail for X gantry (EVA now only supports MGN12)

**Comment by ViralEntity** [comment]
Great point, will fix today
