### ISSUE TITLE
[Issue]: front idlers have defect

### ISSUE THREAD

**Issue by Renidd** [Gutter-Guys/Gutter_Rat#26]
### What happened?

the front left and right idlers have a slope that gets in the way of mounting.
![frontidler](https://user-images.githubusercontent.com/94737492/155975687-45709897-3075-473a-9613-68faa0fa1c7f.PNG)
 

### Version

present in all ver's on gethub

### Which variant are you using?

GR9

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Renidd** [comment]
Attached

**Comment by Renidd** [comment]
![20220228_154816](https://user-images.githubusercontent.com/94737492/156064263-af1993d3-91fe-498c-8b82-1876070c94f9.jpg)
![20220228_154750](https://user-images.githubusercontent.com/94737492/156064281-1950707b-9cf0-432e-b59c-d9550d3fe874.jpg)
![20220228_154732](https://user-images.githubusercontent.com/94737492/156064292-7bd90243-5ca2-47b0-a5ec-2f094819fd95.jpg)

**Comment by Renidd** [comment]
![20220228_155016](https://user-images.githubusercontent.com/94737492/156064462-4a4d094b-93bb-4d41-b5ab-e269a97e4991.jpg)
![20220228_154816](https://user-images.githubusercontent.com/94737492/156064476-185dcc95-46ed-4717-9518-3186923eb531.jpg)
![20220228_154732](https://user-images.githubusercontent.com/94737492/156064491-44a2ba15-3b7f-4558-9e82-416a4889dc67.jpg)

**Comment by Renidd** [comment]
but this is the slope im talking about.. not the one under the idler's
![slope](https://user-images.githubusercontent.com/94737492/156065694-73d2f015-6591-41c2-8d96-754dc0cf0141.png)

**Comment by ViralEntity** [comment]
Gotcha. Thanks easy fix will remove fillet

**Comment by ViralEntity** [comment]
<img width="468" alt="image" src="https://user-images.githubusercontent.com/28642543/156148673-9712b7a3-229a-43bf-a15a-43ccee8ab498.png">
